### ISSUE TITLE
Problem with connect 

### ISSUE THREAD

**Issue by VictorJava** [alipov/ews-android-api#1]
Hi
Alex. 
I need to download the first 10 messages from the exchange server.
So I trying difference library, but nothing to went right.

There is my gradle:
android {
...
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
}
dependencies {
....
    compile files('libs/ews-android-api.jar')  // generated from your library
    compile 'joda-time:joda-time:2.8'
}

I used this code (see attach 1), and following :-1: 
1. In first case I gеt timeout(see attach 2)
   service.setUrl(new URI("http://91.196.101.28/EWS/Exchange.asmx")) - my link http
   microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. Connect to 91.196.101.28:80 [/91.196.101.28] failed: failed to connect to /91.196.101.28 (port 80) after 100000ms: isConnected failed: ETIMEDOUT (Connection timed out)
2. Second case I get NoClassDefFoundError(see attach 3)

But in this time I have already use this account from default android mail client / k9 / mailwise.
So, server is working.
![crash_report1](https://cloud.githubusercontent.com/assets/8449621/10367599/174d7fe2-6dda-11e5-98c9-98617f1f8f56.png)
![crash_report2](https://cloud.githubusercontent.com/assets/8449621/10367597/1748d500-6dda-11e5-9a4d-8461a414ffd6.png)
![crash_report3](https://cloud.githubusercontent.com/assets/8449621/10367598/174d51ac-6dda-11e5-9438-728e127057eb.png)

Can you help me?
Thanks.

**Comment by alipov** [comment]
Hmm.. interesting.
Let me check it.

**Comment by alipov** [comment]
@VictorJava 

Just checked your code sample in my test (lab) environment - it works flawlessly, so regarding the first issue - please verify that you have connection to the server (i.e. open exchange's URL in browser).

I'll check the NoClassDefFoundError exception later today. Thanks for the report!

**Comment by VictorJava** [comment]
Thanks for your reply.

I gess, I doing something wrong.... Please, could you check it?
Could I send to you my test project? My mail victor2kgroup@gmail.com.
Could you send your mail to me(victor2kgroup@gmail.com)

I very gratefyl for your help.
Thanks!

**Comment by alipov** [comment]
@VictorJava 
Indeed some classes are missing. I'll have to fix that first.

**Comment by VictorJava** [comment]
Ok.
How long does it take?
Can I help you something?  Maybe,... testing or something else? 
Thanks.

**Comment by alipov** [comment]
@VictorJava 
I've just pushed commit with missing classes. Could you please pull them, run './gradlew copySources ews-android-api:build' and check if your https connection works?

**Comment by VictorJava** [comment]
Hi 
Alex.

Sorry for the late reply.
I checked this and have some problem.
Please, see attaches. 
![ews_bild_successful](https://cloud.githubusercontent.com/assets/8449621/10424450/f0683d9e-70d7-11e5-80f5-ce96dcc846d4.png)
After replaced jar I can not to build project. 
There is reason
![ews_package_does_not_exist](https://cloud.githubusercontent.com/assets/8449621/10424448/f0651c40-70d7-11e5-89d7-d01a60313d99.png)
There is my test project. Please, rename properties to "zip".
![myapplication_alipov_jar](https://cloud.githubusercontent.com/assets/8449621/10424583/f50ef54e-70d8-11e5-80b8-d286c2b2a5a6.jpg)

Thanks for your help.

**Comment by alipov** [comment]
@VictorJava 
Your libs/ews-android-api.jar's size is 2.4MB, while its current size should be 3.4MB.
Please rebuild the project and verify that.

**Comment by VictorJava** [comment]
Yes, good spot!
There is my mistake...I so apologize...., sorry.
But I trying with new jar file. 
I get something like this(http and https):
![ews_report_4](https://cloud.githubusercontent.com/assets/8449621/10430521/522d1e8e-7108-11e5-9248-6dfffa0e75a1.png)
But in the same time I already logged from default mail client.
May I give your mail to send test account?

Thanks!

**Comment by alipov** [comment]
Sent you email.
Are you sure that you're not working behind a web proxy?

**Comment by nomanuddin** [comment]
**Hi, I am facing issues in compiling "ews-android-api.jar", initial I was not copying the ews-java-api content so my Jar file was only 2.3MB, But now when I add the project ews-java-api content, I am facing following error.

You can see the hierarchy as well for files I have. Thanks in advance :)**
====================================================================
 Directory of C:\Users\Culha\Desktop\EWS\ews-android-api-master

05/07/2016  06:18 PM    <DIR>          .
05/07/2016  06:18 PM    <DIR>          ..
10/09/2015  10:28 AM                64 .gitignore
10/09/2015  10:28 AM               101 .gitmodules
05/07/2016  06:18 PM    <DIR>          .gradle
10/09/2015  10:28 AM             1,511 build.gradle
05/07/2016  06:18 PM    <DIR>          ews-android-api
05/07/2016  06:16 PM    <DIR>          ews-java-api
10/09/2015  10:28 AM    <DIR>          gradle
10/09/2015  10:28 AM               855 gradle.properties
10/09/2015  10:28 AM             5,080 gradlew
10/09/2015  10:28 AM             2,314 gradlew.bat
10/09/2015  10:28 AM             2,889 README.md
10/09/2015  10:28 AM                27 settings.gradle
               8 File(s)         12,841 bytes
               6 Dir(s)  68,392,456,192 bytes free

C:\Users\Culha\Desktop\EWS\ews-android-api-master>cd ews-java-api

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-java-api>dir
 Volume in drive C has no label.
 Volume Serial Number is 9E0D-6461

 Directory of C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-java-api

05/07/2016  06:16 PM    <DIR>          .
05/07/2016  06:16 PM    <DIR>          ..
03/19/2016  04:43 AM               412 .gitignore
03/19/2016  04:43 AM    <DIR>          .idea
03/19/2016  04:43 AM             2,051 .travis.yml
03/19/2016  04:43 AM               189 CONTRIBUTING.md
03/19/2016  04:43 AM             2,460 deploy_snapshot.sh
03/19/2016  04:43 AM             2,426 ews-java-api.iml
03/19/2016  04:43 AM    <DIR>          images
03/19/2016  04:43 AM             1,081 license.txt
03/19/2016  04:43 AM            18,440 pom.xml
03/19/2016  04:43 AM             1,169 readme.md
03/19/2016  04:43 AM    <DIR>          src
               8 File(s)         28,228 bytes
               5 Dir(s)  68,392,456,192 bytes free

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-java-api>cd ..

C:\Users\Culha\Desktop\EWS\ews-android-api-master>gradlew copySources ews-android-api:build
:copySources UP-TO-DATE                                                                              
:ews-android-api:repackageTask UP-TO-DATE     
:ews-android-api:compileJava                                                                     
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:59: error: package android.org.apach
e.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:49: error: package android.or
g.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:36: error: package android.or
g.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:39: error: package and
roid.org.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:268: error: cannot find symbol
    IOUtils.closeQuietly(httpClient);        
    ^                                        
  symbol:   variable IOUtils                 
  location: class ExchangeServiceBase        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:269: error: cannot find symbol
    IOUtils.closeQuietly(httpPoolingClient); 
    ^                                        
  symbol:   variable IOUtils                 
  location: class ExchangeServiceBase        
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:654: error: cannot find symbo
l
      IOUtils.closeQuietly(request);         
      ^                                      
  symbol:   variable IOUtils                 
  location: class ServiceRequestBase<T>      
  where T is a type-variable:                
    T extends Object declared in class ServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:239: error: cannot find symbo
l
      IOUtils.closeQuietly(this.loadToStream);
      ^                                      
  symbol:   variable IOUtils                 
  location: class FileAttachment             
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:245: error: cannot fin
d symbol
      IOUtils.closeQuietly(responseCopy);    
      ^                                      
  symbol:   variable IOUtils                 
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:                
    T extends Object declared in class HangingServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:269: error: cannot fin
d symbol
      IOUtils.closeQuietly(this.response);   
      ^                                      
  symbol:   variable IOUtils                 
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:                
    T extends Object declared in class HangingServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:282: error: cannot fin
d symbol
      IOUtils.closeQuietly(this.response);   
      ^                                      
  symbol:   variable IOUtils                 
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:                
    T extends Object declared in class HangingServiceRequestBase
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors                                    
:ews-android-api:compileJava FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':ews-android-api:compileJava'.
> Compilation failed; see the compiler error output for details.
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED  
              
Total time: 9.796 secs

**Comment by alipov** [comment]
@nomanuddin 
Please open a separate issue and delete your (unrelated) message from this thread.

**Comment by Sharathnasa** [comment]
Hello @alipov 

Even after newly building the jar, still the jar size is 2.4mb. And i'm getting the same exception as @VictorJava posted in the screen shot. please help me in this regard.
Regards,
Sharath

**Comment by alipov** [comment]
@Sharathnasa 
You're probably skipped the 'git submodule init' & 'git submodule update' step.

**Comment by developer-gomalon** [comment]
@alipov  Yes, i didn't do that.. Let me try and come back to you. Thanks a lot man!!!

**Comment by Sharathnasa** [comment]
@alipov 
I'm getting the below mentioned exception after the appointment.save(). Could you please let me know where is it going wrong.

<img width="972" alt="screen shot 2016-06-19 at 3 17 04 pm" src="https://cloud.githubusercontent.com/assets/7545011/16176692/a5640bd6-3632-11e6-95d7-34220592bc8c.png">

Regards,
Sharath

**Comment by alipov** [comment]
@Sharathnasa 
Please open a separate issue for this error (including full stack trace). Also, it will help if you'll post a sample code that you're trying to invoke (remember to exclude any sensitive info).

**Comment by Sharathnasa** [comment]
@alipov 
Sure i will open up new issue for this. Thanks.

I was going through the issue stack, i found that, the issue which i'm facing is similar to #3  

So i think, its required to open new issue, since that issue is still in open status.

Regards,
Sharath

**Comment by alipov** [comment]
The DNS/Applet issues fixed in #3.
