### ISSUE TITLE
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null

### ISSUE THREAD

**Issue by Lugo239** [alipov/ews-android-api#11]
Hi there!

Iam able to send an Email via this api, but when i try to get my calendar appointments iam getting this error:

`microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null`

This is my code, it happens directly in the calendarFolder line:

`CalendarFolder calendarFolder = CalendarFolder.bind(ewsService, WellKnownFolderName.Calendar);
  CalendarView cView = new CalendarView(startDate, endDate, NUM_APPTS);
  cView.setPropertySet(new PropertySet(AppointmentSchema.Subject, AppointmentSchema.Start, AppointmentSchema.End));
  FindItemsResults<Appointment> appointments = calendarFolder.findAppointments(cView);
  for(Appointment item : appointments)
                    {
                        Log.i(TAG, "APPOINTMENTTOSTRING: " + item.toString());
                    }`

Regards!

**Comment by alipov** [comment]
Could you please post full stack trace?

**Comment by Lugo239** [comment]
Mybad sorry!
`05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:505)
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.ExchangeService.bindToFolder(ExchangeService.java:523)
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:60)
 05-05 13:29:01.546 24158-24158/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.service.folder.CalendarFolder.bind(CalendarFolder.java:108)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.test.ews.app.Fundamental.EWSClass$2.run(EWSClass.java:148)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.test.ews.app.Fundamental.EWSClass.listFirstInboxItems(EWSClass.java:204)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.test.ews.app.MainActivity.testEWS(MainActivity.java:288)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.test.ews.app.MainActivity.onButtonClick(MainActivity.java:151)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.view.View$1.onClick(View.java:4261)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.view.View.performClick(View.java:5210)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.view.View$PerformClick.run(View.java:20976)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.os.Looper.loop(Looper.java:145)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6145)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
 05-05 13:29:01.556 24158-24158/com.test.ews.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

**Comment by alipov** [comment]
This is not the full stack trace (inner exception should be printed as well).

**Comment by Lugo239** [comment]
`05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err: Caused by: android.os.NetworkOnMainThreadException
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at android.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.HttpClientWebRequest.executeRequest(HttpClientWebRequest.java:292)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.getEwsHttpWebResponse(ServiceRequestBase.java:720)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:639)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:     at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
 05-05 13:47:14.746 5957-5957/com.test.ews.app W/System.err:    ... 23 more`

**Comment by alipov** [comment]
> Caused by: android.os.NetworkOnMainThreadException

You're trying to initiate a network call from main thread. You can't do that.

**Comment by Lugo239** [comment]
I am wondering because i just started a new thread the same way i run the email-method.

`Thread thread = new Thread(new Runnable()
{
    @Override
    public void run()
    {
        try
        {
           >>CODE<<
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }
});
thread.start();`

**Comment by alipov** [comment]
Try to debug it.
You're clearly invoking the API on main thread (5957 is the main one - as seen in your logs).

**Comment by Lugo239** [comment]
Okay, thanks for the help man!
