### ISSUE TITLE
Build Ews-android-api Error:

### ISSUE THREAD

**Issue by nomanuddin** [alipov/ews-android-api#13]
When I tried to build the ews-android-api, I faced following error:

I added ews-java-api to the its folder after downloading it from [https://github.com/OfficeDev/ews-java-api](url).

Now When I excute the gradlew command I faced following error, I think I am missing some basic step, I have spent hours on this, I hope you will help

C:\Users\Culha\Desktop\EWS\ews-android-api-master>gradlew copySources ews-android-api:build
:copySources UP-TO-DATE

:ews-android-api:repackageTask UP-TO-DATE

:ews-android-api:compileJava

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:59: error: package android.org.apach
e.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
^

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:49: error: package android.or
g.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
^

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:36: error: package android.or
g.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
^

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:39: error: package and
roid.org.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
^

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:268: error: cannot find symbol
IOUtils.closeQuietly(httpClient);

^

symbol: variable IOUtils

location: class ExchangeServiceBase

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:269: error: cannot find symbol
IOUtils.closeQuietly(httpPoolingClient); 
^

symbol: variable IOUtils

location: class ExchangeServiceBase

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:654: error: cannot find symbo
l
IOUtils.closeQuietly(request);

^

symbol: variable IOUtils

location: class ServiceRequestBase

where T is a type-variable:

T extends Object declared in class ServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:239: error: cannot find symbo
l
IOUtils.closeQuietly(this.loadToStream);
^

symbol: variable IOUtils

location: class FileAttachment

C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:245: error: cannot fin
d symbol
IOUtils.closeQuietly(responseCopy);

^

symbol: variable IOUtils

location: class HangingServiceRequestBase
where T is a type-variable:

T extends Object declared in class HangingServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:269: error: cannot fin
d symbol
IOUtils.closeQuietly(this.response);

^

symbol: variable IOUtils

location: class HangingServiceRequestBase
where T is a type-variable:

T extends Object declared in class HangingServiceRequestBase
C:\Users\Culha\Desktop\EWS\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:282: error: cannot fin
d symbol
IOUtils.closeQuietly(this.response);

^

symbol: variable IOUtils

location: class HangingServiceRequestBase
where T is a type-variable:

T extends Object declared in class HangingServiceRequestBase
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

:ews-android-api:compileJava FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':ews-android-api:compileJava'.

Compilation failed; see the compiler error output for details.
Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.796 secs

**Comment by alipov** [comment]
Thanks for reporting this.
There were changes in ews-java-api since my last update. I'll do my best to update the repo this week.

**Comment by Thewizeguy** [comment]
Any idea if this was ever addressed? I seem to be getting the same error and know >< much about how to fix it. I'd love to help but you don't want me in there.
