### ISSUE TITLE
Error while building ews-android-api

### ISSUE THREAD

**Issue by saiajaym** [alipov/ews-android-api#14]
I tried building the api, but i always end up with same error, please look it into this issue and help me out.
gradlew copySources ews-android-api:build

:copySources UP-TO-DATE  
:ews-android-api:repackageTask UP-TO-DATE  
:ews-android-api:compileJava  
warning: [options] bootstrap class path not set in conjunction with -source 1.7
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:59: error: package android.org.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:49: error: package android.org.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:36: error: package android.org.apache.commons.io does not exist
import android.org.apache.commons.io.IOUtils;
                                    ^  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:39: error: package android.org.apache.commons.io does not ex
ist
import android.org.apache.commons.io.IOUtils;
                                    ^  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:268: error: cannot find symbol
    IOUtils.closeQuietly(httpClient);  
    ^  
  symbol:   variable IOUtils  
  location: class ExchangeServiceBase  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\ExchangeServiceBase.java:269: error: cannot find symbol
    IOUtils.closeQuietly(httpPoolingClient); 
    ^  
  symbol:   variable IOUtils  
  location: class ExchangeServiceBase  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\ServiceRequestBase.java:654: error: cannot find symbol
      IOUtils.closeQuietly(request);  
      ^  
  symbol:   variable IOUtils  
  location: class ServiceRequestBase<T>  
  where T is a type-variable:  
    T extends Object declared in class ServiceRequestBase
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\property\complex\FileAttachment.java:239: error: cannot find symbol
      IOUtils.closeQuietly(this.loadToStream);
      ^  
  symbol:   variable IOUtils  
  location: class FileAttachment  
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:245: error: cannot find symbol
      IOUtils.closeQuietly(responseCopy);  
      ^  
  symbol:   variable IOUtils  
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:  
    T extends Object declared in class HangingServiceRequestBase
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:269: error: cannot find symbol
      IOUtils.closeQuietly(this.response);  
      ^  
  symbol:   variable IOUtils  
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:  
    T extends Object declared in class HangingServiceRequestBase
C:\Users\sai.m\Desktop\ews-android-api-master\ews-android-api\src\main\java\microsoft\exchange\webservices\data\core\request\HangingServiceRequestBase.java:282: error: cannot find symbol
      IOUtils.closeQuietly(this.response);  
      ^  
  symbol:   variable IOUtils  
  location: class HangingServiceRequestBase<T>
  where T is a type-variable:  
    T extends Object declared in class HangingServiceRequestBase
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors  
1 warning  
:ews-android-api:compileJava FAILED          

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':ews-android-api:compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:  
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED  

Total time: 16.044 secs

**Comment by alipov** [comment]
Thanks for reporting this.
There were changes in ews-java-api since my last update. I'll do my best to update the repo this week.

**Comment by alipov** [comment]
Duplicate. You can track it at #13
