### ISSUE TITLE
I have a problem and need help

### ISSUE THREAD

**Issue by yinghannr** [alipov/ews-android-api#17]
Hi @alipov 

I packed it out to 2.4M, can you give me a bag of 3.2M you pack? Thank you
![jar](https://cloud.githubusercontent.com/assets/21034655/23111160/acee8f3e-f761-11e6-8075-abe307de79fc.jpg)

**Comment by yinghannr** [comment]
My mailbox: yinghannr@163.com

**Comment by alipov** [comment]
@yinghannr just add both of the jars as dependencies in your Android project.

**Comment by yinghannr** [comment]
@alipov 
I introduced the 2.4M jar, and can not connect to ExchangeService, I feel I use
./gradlew copySources ews-android-api:build hit bag problem

![default](https://cloud.githubusercontent.com/assets/21034655/23120756/9a1be82a-f798-11e6-911c-142e53a4dff3.jpg)

**Comment by alipov** [comment]
Which error do you receive when you're trying to connect?
