### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by mhay1997** [alipov/ews-android-api#24]
Hi.
when i try to build the project i give this error:
`
![image](https://user-images.githubusercontent.com/32324729/40165712-f0fa6b8e-59d1-11e8-8da3-c7e586c036e6.png)

`

Can you give the .jar file please?
I don't have enough time.

**Comment by alipov** [comment]
You've most probably missed ews-java-api submodule initialization:
```
git submodule init
git submodule update
```
