### ISSUE TITLE
when sending email, how can I callback the response to handle the case, like timeout or request failed.

### ISSUE THREAD

**Issue by CamiYe** [alipov/ews-android-api#25]
I set timeout time, but I don't know when the request is timeout. Because I need to handle something that time.

**Comment by alipov** [comment]
Please note that this project is simply a wrapper around [ews-java-api](https://github.com/OfficeDev/ews-java-api). Therefore, it is better to post questions regarding the APIs at [StackOverflow](https://stackoverflow.com/questions/tagged/ewsjavaapi) or on ews-java-api's issues page.
