### ISSUE TITLE
Failed resolution of: Lorg/xbill/DNS/Lookup

### ISSUE THREAD

**Issue by KushtrimPacaj** [alipov/ews-android-api#27]
I'm getting a missing class, as in the exception below.

>      Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/xbill/DNS/Lookup;
>         at microsoft.exchange.webservices.data.dns.DnsClient.dnsQuery(DnsClient.java:56)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findBestMatchingSrvRecord(AutodiscoverDnsClient.java:129)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findAutodiscoverHostFromSrv(AutodiscoverDnsClient.java:102)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getRedirectionUrlFromDnsSrvRecord(AutodiscoverService.java:767)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getSettings(AutodiscoverService.java:1180)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1044)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetSoapUserSettings(AutodiscoverService.java:988)
>         at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1851)
>         at microsoft.exchange.webservices.data.core.ExchangeService.getAutodiscoverUrl(ExchangeService.java:3616)
>         at microsoft.exchange.webservices.data.core.ExchangeService.autodiscoverUrl(ExchangeService.java:3541)
>   

Adding dnsjava as direct dependency seems to work:
`implementation 'dnsjava:dnsjava:2.1.9'`

Maybe this should be added to the README?

P.S. Thanks for this library. Started doing this myself before I found your project. Saved me a ton of time.

**Comment by alipov** [comment]
Hey @KushtrimPacaj,

Great catch, thanks for reporting! (I've used version 2.1.6, since this is what I've tested with in the past).

> P.S. Thanks for this library. Started doing this myself before I found your project. Saved me a ton of time.  

Glad to hear that! :)
