### ISSUE TITLE
How to use modern authentication instead of basic authentication in ews-android-api 

### ISSUE THREAD

**Issue by arunsankar8** [alipov/ews-android-api#29]
Hi @alipov 

This is not a issue, just asking some tips and support from you. I have been using the ews-android-api in my application to get the events etc.. According to the docs, the basic authentication will be deprecated on the coming October 2020. I believe the basic authentication have been using, So how can I use modern authentication instead of basic authentication in my application to continue using the ews-android-api in my projects. Looking forward to your suggestions and support.

The sample code used for login
```

  public void login() throws Exception {
        ExchangeService service = createService();
        Mailbox mailbox = new Mailbox(user.getMailbox());
        FolderId folderId = new FolderId(WellKnownFolderName.Calendar, mailbox);
        CalendarFolder folder = CalendarFolder.bind(service, folderId);
    }
```

**Comment by alipov** [comment]
Hi @arunsankar8, 

Since the question relates to the core functionality (rather than to Android adjustments), I'd suggest you to direct it to [ews-java ](https://github.com/OfficeDev/ews-java-api) maintainers.

**Comment by arunsankar8** [comment]
Thanks @alipov.

**Comment by arunsankar8** [comment]
Hi @alipov,
I have raised the same question in the ews-java repo, but there aren't any responses till now from their side. Is there any way to implement modern authentication in the application you know of, the steps described in [Microsoft documentation](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth) to implement modern authentication is for C#. Can you please take a look at it. Can we implement modern authentication in android.? It will be really helpful if you could help.

**Comment by alipov** [comment]
Hi @arunsankar8,

I don't have any immediate plans implementing modern authentication support.

I guess you can look into [microsoft-authentication-library-for-android](https://github.com/AzureAD/microsoft-authentication-library-for-android) or [AppAuth-Android](https://github.com/openid/AppAuth-Android) and see if it can be used to easily add such support. Also, it seems that some attempts to add OAuth2 support were made [here](https://github.com/OfficeDev/ews-java-api/pull/606) and [here](https://stackoverflow.com/questions/41875795/office-365-calendar-api-using-ews-and-oauth-2).

**Comment by arunsankar8** [comment]
Hi @alipov 

Thanks for the support, I will try to use these resources. Thanks

**Comment by arunsankar8** [comment]
Hi @alipov the MSAL library from the above documentation is used for authentication in Microsoft Graph API, can we use that for the EWS authentication also? 

https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth  This was the Microsoft documentation on implementing the modern auth, can we use this in our Android application? Any idea on these

**Comment by alipov** [comment]
Perhaps. I don't have any prior experience with this library.
