### ISSUE TITLE
ClassNotFoundException while calling ExchangeService#autodiscoverUrl

### ISSUE THREAD

**Issue by alipov** [alipov/ews-android-api#3]
The following exception thrown while calling `ExchangeService#autodiscoverUrl`:

<pre>
E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.applet.Applet" on path: DexPathList[[zip file "/data/app/info.osom.ews-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime:     at com.sun.naming.internal.ResourceManager.getInitialEnvironment(ResourceManager.java:126) 
E/AndroidRuntime:     at android.javax.naming.InitialContext.init(InitialContext.java:222) 
E/AndroidRuntime:     at android.javax.naming.InitialContext.<init>(InitialContext.java:202) 
E/AndroidRuntime:     at android.javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:87) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.dns.DnsClient.dnsQuery(DnsClient.java:79) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findBestMatchingSrvRecord(AutodiscoverDnsClient.java:129) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findAutodiscoverHostFromSrv(AutodiscoverDnsClient.java:102) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getRedirectionUrlFromDnsSrvRecord(AutodiscoverService.java:766) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getSettings(AutodiscoverService.java:1179) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1043) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetSoapUserSettings(AutodiscoverService.java:987) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1849) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.core.ExchangeService.getAutodiscoverUrl(ExchangeService.java:3615) 
E/AndroidRuntime:     at microsoft.exchange.webservices.data.core.ExchangeService.autodiscoverUrl(ExchangeService.java:3541) 
E/AndroidRuntime:     at info.osom.ews.MainActivity$1.run(MainActivity.java:60) 
E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 
</pre>

**Comment by tmakin** [comment]
Just tried autodiscovery using an office 365 account and I get the same error. Test was done using API 23 Nexus emulator.

In general, this error looks quite nasty. Do you think it will necessary to somehow patch the EWS dns client with something like http://www.dnsjava.org/? Or is there some magic that can be done with `java.applet`?

**Comment by tuckercr** [comment]
I have a very similar issue with auto resolution, although mine threw NoClassDefFoundError instead of @alipov's ClassNotFoundException

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/applet/Applet;
 at com.sun.naming.internal.ResourceManager.getInitialEnvironment(ResourceManager.java:126)
 at android.javax.naming.InitialContext.init(InitialContext.java:222)
 at android.javax.naming.InitialContext.<init>(InitialContext.java:202)
 at android.javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:87)
 at microsoft.exchange.webservices.data.dns.DnsClient.dnsQuery(DnsClient.java:79)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findBestMatchingSrvRecord(AutodiscoverDnsClient.java:129)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverDnsClient.findAutodiscoverHostFromSrv(AutodiscoverDnsClient.java:102)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getRedirectionUrlFromDnsSrvRecord(AutodiscoverService.java:766)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getSettings(AutodiscoverService.java:1179)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1043)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetSoapUserSettings(AutodiscoverService.java:987)
 at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1849)
 at microsoft.exchange.webservices.data.core.ExchangeService.getAutodiscoverUrl(ExchangeService.java:3615)
 at microsoft.exchange.webservices.data.core.ExchangeService.autodiscoverUrl(ExchangeService.java:3541)
```

**Comment by tuckercr** [comment]
I have a working solution for this, although I'm not sure how to integrate it into your build process since it involves modifying the code in ews-java-api

I modified DnsClient.java, removing the getEnv() method and replacing dnsQuery(..) with code that uses http:///www.dnsjava.com instead.  For this I simply copied the source code of dnsjava into the ews-java-api source folder.

One limitation is that my code ignores the dnsServerAddress parameter.  In all my tests this was always null.

Please find attached the source code for DnsClient.java.

[DnsClient.java.txt](https://github.com/alipov/ews-android-api/files/61628/DnsClient.java.txt)

**Comment by wwahmed** [comment]
Can add that I am also experiencing this issue on some Android levels .. Hopefully we can find a solution for it too.

**Comment by developer-gomalon** [comment]
@tuckercr 
Could you help in adding your to the to the ews-java-api locally and rebuild the .jar. I tried to change the the code but it is giving error because i don't have proper imports.

Ex:import org.xbill.DNS.Lookup;
import org.xbill.DNS.Record;
import org.xbill.DNS.SRVRecord;
import org.xbill.DNS.Type;

For these i tired to add the library dnsjava-2.1.1.jar and was not able to provide the path in gradle file and sync the same. Could you shed some light

Regards,
Sharath

**Comment by alipov** [comment]
@developer-gomalon 
As @tuckercr wrote, he added [dnsjava](http://mvnrepository.com/artifact/dnsjava/dnsjava/2.1.6) dependency. I'll test this workaround, and then will add a fix.

**Comment by developer-gomalon** [comment]
@alipov 
Yes, after adding the dependency to the gradle file, they is no option to sync right in the ews-android-api.
Or Am I doing it in a wrong way!!!
I just added the gradle dependency and changed the code in the DnsClient.java. Since i didn't had the lib ie. there is no option to sync it was throwing the error

And one more question, does this lib works for exchange version 2013 and above?

**Comment by alipov** [comment]
As @tmakin and @tuckercr suggested (thanks guys!), I've replaced the javax.naming classes with dnsjava library. 

@developer-gomalon 
Yes, it supports Exchange 2013.
Please test it. The fix is on separate branch, so do:
`git checkout dns-query-fix`
Also, add dnsjava as dependency to your app:
`compile 'dnsjava:dnsjava:2.1.6'`
Let me know if you have any issues with this, and if it works - I'll merge it to master.

**Comment by Satarus** [comment]
@alipov 
I tested your dns-query-fix and it worked for the missing java.applet dependency but afterwards I got #1 back missing class `Landroid/javax/naming/ldap/LdapName;` so I figured that I should leave javax naming in and adjusted your branch. [You can see the change here](https://github.com/Satarus/ews-android-api/commit/413b193a1fa96f6153c241f9c90029e0782d0497). This worked for me in conjunction with your workaround from #5.

**Comment by rehand** [comment]
@Satarus 
should your modified branch "dns-query-fix" work like it is checked in? I tried building it, but I get the following errors:
`ews-android-api/src/main/java/android/org/apache/harmony/jndi/internal/parser/LdapNameParser.java:24: error: cannot find symbol
import android.javax.naming.InvalidNameException;
                           ^
  symbol:   class InvalidNameException
  location: package android.javax.naming
ews-android-api/src/main/java/android/org/apache/harmony/jndi/internal/parser/LdapNameParser.java:25: error: cannot find symbol
import android.javax.naming.Name;
                           ^
  symbol:   class Name
  location: package android.javax.naming
ews-android-api/src/main/java/android/org/apache/harmony/jndi/internal/parser/LdapNameParser.java:26: error: cannot find symbol
import android.javax.naming.NameParser;
                           ^
  symbol:   class NameParser
  location: package android.javax.naming`

**Comment by Satarus** [comment]
@rehand 
I cannot build it either, looks like jcenter removed the javax dependency so we have to find it somewhere else.

**Comment by nherbar** [comment]
@alipov 
Does anyone be able to fix this issue and use properly service.autodiscoverUrl()?
Because I have the same problem and don´t know how to solve it :( 

I´ve followed the steps than you mention in the comments above so I´m in the same point of:
 java.lang.NoClassDefFoundError: android.javax.naming.ldap.LdapName 

Thanks a lot!!

**Comment by alipov** [comment]
I've re-added the jndi dependency, please let me know if this works for you and I'll merge it to master.
