### ISSUE TITLE
ServiceRequestException: The request failed. null

### ISSUE THREAD

**Issue by danxfisher** [alipov/ews-android-api#4]
Related: https://github.com/OfficeDev/ews-java-api/issues/301

I'm getting the same errors.  Is there working code to get Calendar appointments that you've come across or tested?

**Comment by alipov** [comment]
The referenced issue seems to be fixed.
Can you post a sample code and exception stack trace?

Thanks!

**Comment by Lugo239** [comment]
Hey guys! 
Does it work now? I have the same problem.

With the StricMode-Call i am able to get the calendar events:
`StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();`
`StrictMode.setThreadPolicy(policy);`
`new Thread(new Runnable() [...]`

But it leads into this:
`I/Choreographer: Skipped 162 frames!  The application may be doing too much work on its main thread.`

Now i try to run this as AsyncTask, but it leads into this:
`microsoft.exchange.webservices.data.exception.ServiceRequestException: The request failed. null`

Note: Sending an email or creating a meeting works with just run a new Thread.

Greetings
Lugo

**Comment by alipov** [comment]
@Lugo239 Can you post full stack trace for `microsoft.exchange.webservices.data.exception.ServiceRequestException: The request failed. null` ?

**Comment by kabhimanyu** [comment]
here is the stacktrace alipov
 microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. null
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:147)
08-26 21:15:15.587 15999-15999/com.ctrlswitch.org.meetingdrawerlayoutfinal W/System.err:     at microsoft.exchange.webservices.data.core.service.item.EmailMessage.send(EmailMessage.java:258)

**Comment by alipov** [comment]
Thanks @kabhimanyu 
Could you please post full exception stack trace (including internal exception's stack trace)?
